platform :ios, '8.0'

use_frameworks!

abstract_target 'xxxx' do
    
    pod 'ObjectMapper'
    pod 'SnapKit'
    pod 'Alamofire'
    
    target 'Swift-Learning-Demo' do
        
    end

    target 'Swift-Learning-DemoTests' do
        
    end
    
end
